### PR TITLE
Switch to absolute imports

### PR DESCRIPTION
**Pull request by calvinytong**
Addresses #40. Big little change, tests are passing and example works, so assuming it is fine. This should go in after my last pr as it is branched off of it. fyi @paninski-lab/yass-devs, from now on use absolute imports whenever possible.

### CODE REVIEW

**Comment by edublancas** [comment]
Thanks, will merge this after merging nishchal's PR

**Comment by edublancas** [comment]
Can you update your PR? I merged @nd2506 new model and some import statements changed

**Comment by calvinytong** [comment]
Will do. Should I merge after updating? Also what merge style do you prefer?

**Comment by calvinytong** [comment]
@edublancas I merged the changes. There are some flake issues, do you want me to try to fix them? Or do you want to stomp them yourself?

**Comment by edublancas** [comment]
Yes, please fix them

**Comment by calvinytong** [comment]
@edublancas This is RDY, shall I merge?

**Pull request merged**
