### PR TITLE
Changes to Cluster modeuls

### PR DESCRIPTION
**Pull request by jinhyunglee**

### CODE REVIEW

**Comment by jinhyunglee** [comment]
Not sure about the error that I am getting here..

**Comment by edublancas** [comment]
Build is failing, log is printing a lot of these:

```
DEBUG:yass.config.config:Loaded with params: {'a': 1, 'beta': 1, 'nu': 5, 'lambda0': 0.01, 'V': 2} 
DEBUG:yass.config.config:Loaded with params: {'max_n_spikes': 10000, 'n_split': 5, 'prior': {'a': 1, 'beta': 1, 'nu': 5, 'lambda0': 0.01, 'V': 2}, 'masking_threshold': [0.9, 0.5], 'coreset': {'threshold': 0.95, 'clusters': 10}, 'triage': {'percent': 0.1, 'nearest_neighbors': 20}, 'method': 'location'} 
DEBUG:yass.config.config:Loaded with params: {'a': 1, 'beta': 1, 'nu': 5, 'lambda0': 0.01, 'V': 2} 
DEBUG:yass.config.config:Loaded with params: {'max_n_spikes': 10000, 'n_split': 5, 'prior': {'a': 1, 'beta': 1, 'nu': 5, 'lambda0': 0.01, 'V': 2}, 'masking_threshold': [0.9, 0.5], 'coreset': {'threshold': 0.95, 'clusters': 10}, 'triage': {'percent': 0.1, 'nearest_neighbors': 20}, 'method': 'location'} 
DEBUG:yass.config.config:Loaded with params: {'a': 1, 'beta': 1, 'nu': 5, 'lambda0': 0.01, 'V': 2} 
DEBUG:yass.config.config:Loaded with params: {'max_n_spikes': 10000, 'n_split': 5, 'prior': {'a': 1, 'beta': 1, 'nu': 5, 'lambda0': 0.01, 'V': 2}, 'masking_threshold': [0.9, 0.5], 'coreset': {'threshold': 0.95, 'clusters': 10}, 'triage': {'percent': 0.1, 'nearest_neighbors': 20}, 'method': 'location'} 
DEBUG:yass.config.config:Loaded with params: {'a': 1, 'beta': 1, 'nu': 5, 'lambda0': 0.01, 'V': 2} 
DEBUG:yass.config.config:Loaded with params: {'max_

The log length has exceeded the limit of 4 MB (this usually means that the test suite is raising the same exception over and over).

The job has been terminated
```

**Comment by jinhyunglee** [comment]
I am not.. Not sure where it is being printed since it did not put that log in.
can you check?

**Comment by edublancas** [comment]
the `Loaded with params:` is printed whenever the config object is initialized. Looks like it's been rewritten over and over again, that seems weird. Did you merge code from other branch?

**Comment by calvinytong** [comment]
Also fixes #170 I believe

**Comment by calvinytong** [comment]
Let's just merge master into this and see if that fixes it.

**Comment by calvinytong** [comment]
Hmm combed through the touched code and couldn't find any obvious causes. How/Where do we init the config?

**Comment by edublancas** [comment]
`yass/pipeline.py`, first line sets the config

**Comment by calvinytong** [comment]
Hmm, but this is printing on init of FrozenJSON. Any reason that should be happening so much? It also happens on master, but it does finish locally. If we remove the log it should pass.

**Comment by calvinytong** [comment]
Okay, commenting the log lets the build pass. This is a hack around a bigger issue, but the build passes on this pr now.

**Comment by edublancas** [comment]
Closing it since @jinhyunglee mention is no longer required to merge this

**Pull request closed without merging**
