### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by nd2506**
Added 2+3 model

### CODE REVIEW

**Comment by edublancas** [comment]
Thanks @nd2506, since this is a big PR, it's going to take me some time to review. I will do it tonight and tomorrow morning. Will get back to you with comments, if any.

**Comment by edublancas** [comment]
I quickly wen through the tests results and spotted some issues:

* Your code does not follow PEP8, [check this out](https://github.com/paninski-lab/yass/blob/master/CONTRIBUTING.rst#code-style)
* Some tests are failing, I think you added an option in the config file called `clusterType` but the sample config files in the tests do not have that field so you need to add that one, we are using `underscore_case` in the yaml file so might be better to change it to `clustering_method`
* There are some conflicting files with the dev branch, make sure your branch is synced with the dev branch since I've made some changes recently, [take a look at this](https://help.github.com/articles/syncing-a-fork/)

**Comment by calvinytong** [comment]
Re PEP8, I recommend setting up this [package](https://github.com/google/yapf). You can set it to autoformat pep8 everytime you save. Also for future reference: before opening a pr you should always check that tests are passing on your branch and you have no conflicts with the branch you are merging to. The metric to use here is "if no one has comments, can I merge it as is". If those conditions are not met, you should open with some kind of WIP tag to indicate that what you have is not ready to be merged

**Comment by edublancas** [comment]
Another comment, travis is having issues with their new environment, the only solution I've found so far is to test against python 3.5 instead of 3.6. @nd2506, please change the `travis.yml` file in your branch, where it says `3.6` it should now say `3.5`.

**Pull request closed without merging**
